version: '3.9'
services:
  api:
    build: .
    image: goldrecovery/api:latest
    container_name: goldrecovery_api
    environment:
      - MODEL_PATH=/app/models/metallurgical_model.pkl
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: ["uvicorn", "app.fastapi_app:app", "--host", "0.0.0.0", "--port", "8000"]
